name: publish-branch
on:
  push:
    branches:
      - teaser
  workflow_dispatch:
jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    with:
      build_branch: build/teaser
    secrets: inherit